apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: easyshop
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: mongodb-pv
  storageClassName: ""   # <--- Explicitly disables storage class assignment
  resources:
    requests:
      storage: 5Gi
